<?xml version="1.0" encoding="UTF-8"?>
<!-- Completar este documento para registrar hoteles,
    donde tengas nombre, teléfono, dirección(calle y número),
    ciudad, país, numero de estrellas, descripción del hotel,
    número habitaciones individuales, habitaciones dobles,
    habitaciones triples, suites.
    Probar si es un documento bien formado. Sigo haciendo cambios
-->
<!DOCTYPE hoteles [
  <!ELEMENT hoteles (hotel)>
  <!ELEMENT hotel (nombre,dirección,teléfono,codigo_p)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT direccion (#PCDATA)>
  <!ELEMENT telefono (#PCDATA)>
  <!ELEMENT codigo_p (#PCDATA)>
  <!ELEMENT habitaciones (#PCDATA)>
]>
<hotel>
  <nombre>Hotel Talaso</nombre>
  <direccion>RUA CASTELLANOS</direccion>
  <telefono>988594877</telefono>
  <codigo_p>36209</codigo_p>
  <habitaciones>3</habitaciones>
</hotel>
<hotel>
  <nombre>Hotel LOUXO</nombre>
  <direccion>CALLE ABRIL</direccion>
  <telefono>998564812</telefono>
  <codigo_p>36210</codigo_p>
  <habitaciones>6</habitaciones>
</hotel>
